name: Main Workflow
on:
  push:
    branches:
      - main
      - develop
  pull_request:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish:
    if: github.event_name == 'release'
    needs: build
    uses: ./.github/workflows/publish.yml
    secrets:
      GH_PUSH_TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
